# Generated by Django 2.1.5 on 2019-02-13 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_restricted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.CharField(max_length=12, unique=True, verbose_name='CAS number')),
                ('name', models.CharField(max_length=255)),
                ('ispoison_nonvol', models.BooleanField(verbose_name='is poison - non-volatile')),
                ('isreactive', models.BooleanField(verbose_name='is reactive')),
                ('issolid', models.BooleanField(verbose_name='is solid')),
                ('isoxidliq', models.BooleanField(verbose_name='is oxidizing liquid')),
                ('isflammable', models.BooleanField(verbose_name='is flammable')),
                ('isbaseliq', models.BooleanField(verbose_name='is base liquid')),
                ('isorgminacid', models.BooleanField(verbose_name='is organic and mineral acid')),
                ('isoxidacid', models.BooleanField(verbose_name='is oxidizing acid')),
                ('ispois_vol', models.BooleanField(verbose_name='is poison - volatile')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('is_inactive', models.BooleanField(verbose_name='Archived')),
                ('del_date', models.DateField(verbose_name='delivery date')),
                ('open_date', models.DateField(null=True, verbose_name='date opened')),
                ('exp_date', models.DateField(null=True, verbose_name='expiration date')),
                ('ret_date', models.DateField(null=True, verbose_name='retest date')),
                ('purity', models.CharField(max_length=255, null=True, verbose_name='purity/percentage')),
                ('init_amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='initial amount')),
                ('used_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='amount used')),
                ('company', models.CharField(max_length=255)),
                ('cat_num', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_res', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='amount to reserve')),
                ('date_res', models.DateField(verbose_name='date of reservation')),
                ('is_complete', models.BooleanField()),
                ('prod_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Product_Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('building_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product_unit',
            name='reservation',
            field=models.ManyToManyField(through='labbyims.Reserve', to='labbyims.Account'),
        ),
        migrations.AddField(
            model_name='location',
            name='product',
            field=models.ManyToManyField(to='labbyims.Product'),
        ),
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Room'),
        ),
    ]
