# Generated by Django 2.1.5 on 2019-03-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watching',
            name='prod_perc',
        ),
        migrations.AlterField(
            model_name='association',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='location',
            name='isbaseliq',
            field=models.BooleanField(default=False, verbose_name='base liquid'),
        ),
        migrations.AlterField(
            model_name='location',
            name='isflammable',
            field=models.BooleanField(default=False, verbose_name='flammable'),
        ),
        migrations.AlterField(
            model_name='location',
            name='isorgminacid',
            field=models.BooleanField(default=False, verbose_name='organic and mineral acid'),
        ),
        migrations.AlterField(
            model_name='location',
            name='isoxidacid',
            field=models.BooleanField(default=False, verbose_name='oxidizing acid'),
        ),
        migrations.AlterField(
            model_name='location',
            name='isoxidliq',
            field=models.BooleanField(default=False, verbose_name='oxidizing liquid'),
        ),
        migrations.AlterField(
            model_name='location',
            name='ispois_vol',
            field=models.BooleanField(default=False, verbose_name='poison - volatile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='ispoison_nonvol',
            field=models.BooleanField(default=False, verbose_name='poison - non-volatile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='isreactive',
            field=models.BooleanField(default=False, verbose_name='reactive'),
        ),
        migrations.AlterField(
            model_name='location',
            name='issolid',
            field=models.BooleanField(default=False, verbose_name='solid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbaseliq',
            field=models.BooleanField(verbose_name='base liquid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isflammable',
            field=models.BooleanField(verbose_name='flammable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isorgminacid',
            field=models.BooleanField(verbose_name='organic and mineral acid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isoxidacid',
            field=models.BooleanField(verbose_name='oxidizing acid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isoxidliq',
            field=models.BooleanField(verbose_name='oxidizing liquid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ispois_vol',
            field=models.BooleanField(verbose_name='poison - volatile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ispoison_nonvol',
            field=models.BooleanField(verbose_name='poison - non-volatile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isreactive',
            field=models.BooleanField(verbose_name='reactive'),
        ),
        migrations.AlterField(
            model_name='product',
            name='issolid',
            field=models.BooleanField(verbose_name='solid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_temp',
            field=models.DecimalField(decimal_places=3, default=25, max_digits=6, verbose_name='Minimum Temperature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_temp',
            field=models.DecimalField(decimal_places=3, default=25, max_digits=6, verbose_name='Maximum Temperature'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='m_unit',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='measurement units'),
        ),
    ]
