# Generated by Django 2.1.5 on 2019-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='del_date',
            field=models.DateField(null=True, verbose_name='delivery date'),
        ),
    ]
