# Generated by Django 2.1.5 on 2019-02-23 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 22, 19, 18, 13, 472274, tzinfo=utc), verbose_name='expiration date'),
        ),
    ]
