# Generated by Django 2.1.6 on 2019-03-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='res_name',
            field=models.CharField(default='Reservation', max_length=255, unique=True, verbose_name='Reservation name'),
        ),
    ]
