# Generated by Django 2.1.5 on 2019-02-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_unit',
            name='m_unit',
            field=models.CharField(max_length=4, null=True, verbose_name='measuring units'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='cat_num',
            field=models.CharField(max_length=255, verbose_name='catalog number'),
        ),
    ]
