# Generated by Django 2.1.5 on 2019-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='is_complete',
            field=models.BooleanField(null=True),
        ),
    ]
