# Generated by Django 2.1.5 on 2019-03-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_unit',
            name='watch',
            field=models.ManyToManyField(through='labbyims.Watching', to='labbyims.Department'),
        ),
    ]
