# Generated by Django 2.1.5 on 2019-02-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='amount used')),
                ('date_used', models.DateField(verbose_name='date of use')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_restricted',
        ),
        migrations.RemoveField(
            model_name='product_unit',
            name='temperature',
        ),
        migrations.AddField(
            model_name='location',
            name='isbaseliq',
            field=models.BooleanField(default=False, verbose_name='is base liquid'),
        ),
        migrations.AddField(
            model_name='location',
            name='isflammable',
            field=models.BooleanField(default=False, verbose_name='is flammable'),
        ),
        migrations.AddField(
            model_name='location',
            name='isorgminacid',
            field=models.BooleanField(default=False, verbose_name='is organic and mineral acid'),
        ),
        migrations.AddField(
            model_name='location',
            name='isoxidacid',
            field=models.BooleanField(default=False, verbose_name='is oxidizing acid'),
        ),
        migrations.AddField(
            model_name='location',
            name='isoxidliq',
            field=models.BooleanField(default=False, verbose_name='is oxidizing liquid'),
        ),
        migrations.AddField(
            model_name='location',
            name='ispois_vol',
            field=models.BooleanField(default=False, verbose_name='is poison - volatile'),
        ),
        migrations.AddField(
            model_name='location',
            name='ispoison_nonvol',
            field=models.BooleanField(default=False, verbose_name='is poison - non-volatile'),
        ),
        migrations.AddField(
            model_name='location',
            name='isreactive',
            field=models.BooleanField(default=False, verbose_name='is reactive'),
        ),
        migrations.AddField(
            model_name='location',
            name='issolid',
            field=models.BooleanField(default=False, verbose_name='is solid'),
        ),
        migrations.AddField(
            model_name='product_unit',
            name='curr_amount',
            field=models.DecimalField(decimal_places=4, default=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='initial amount'), max_digits=10, verbose_name='current amount'),
        ),
        migrations.AddField(
            model_name='product_unit',
            name='max_temp',
            field=models.DecimalField(decimal_places=4, default=25, max_digits=10, verbose_name='Minimum Temperature'),
        ),
        migrations.AddField(
            model_name='product_unit',
            name='min_temp',
            field=models.DecimalField(decimal_places=4, default=25, max_digits=10, verbose_name='Maximum Temperature'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='init_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='initial amount'),
        ),
        migrations.AddField(
            model_name='uses',
            name='prod_un',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Product_Unit'),
        ),
        migrations.AddField(
            model_name='uses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Account'),
        ),
    ]
