# Generated by Django 2.1.5 on 2019-02-13 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labbyims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product_unit',
            name='m_units',
            field=models.CharField(max_length=4, null=True, verbose_name='measurement units'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='exp_date',
            field=models.DateField(null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='open_date',
            field=models.DateField(null=True, verbose_name='date opened'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='reservation',
            field=models.ManyToManyField(through='labbyims.Reserve', to='labbyims.Account'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labbyims.Account'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
