# Generated by Django 2.1.6 on 2019-03-01 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190224_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='product_unit',
            name='batch',
            field=models.CharField(blank=True, max_length=255, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='product_unit',
            name='in_house_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='In House ID'),
        ),
        migrations.AddField(
            model_name='department',
            name='prod_un',
            field=models.ManyToManyField(to='labbyims.Product_Unit'),
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
