# Generated by Django 2.1.5 on 2019-02-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190215_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='del_date',
            field=models.DateField(verbose_name='delivery date'),
        ),
    ]
