# Generated by Django 2.1.5 on 2019-03-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
