# Generated by Django 2.1.5 on 2019-02-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190218_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_unit',
            old_name='name',
            new_name='description',
        ),
    ]
