# Generated by Django 2.1.5 on 2019-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190223_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiration date'),
        ),
    ]
