# Generated by Django 2.1.5 on 2019-02-26 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190224_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prod_un', models.ManyToManyField(to='labbyims.Product_Unit')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
