# Generated by Django 2.1.5 on 2019-03-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190307_1151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='association',
            unique_together={('user', 'dept')},
        ),
    ]
