# Generated by Django 2.1.5 on 2019-03-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_product_unit_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watching',
            name='prod_perc',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10, verbose_name='Percent left'),
        ),
    ]
