# Generated by Django 2.1.5 on 2019-02-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190213_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='m_units',
            field=models.TextField(max_length=4, null=True, verbose_name='measurement units'),
        ),
    ]
