# Generated by Django 2.1.6 on 2019-02-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190219_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_unit',
            name='is_inactive',
        ),
    ]
