# Generated by Django 2.1.5 on 2019-03-05 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0003_auto_20190305_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='users',
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
