# Generated by Django 2.1.6 on 2019-03-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0003_auto_20190312_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='temperature',
            field=models.DecimalField(decimal_places=4, default=25, max_digits=10, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='m_unit',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='measuring units'),
        ),
    ]
