# Generated by Django 2.1.6 on 2019-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0003_watching_prod_perc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_unit',
            name='watch',
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='curr_amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, verbose_name='current amount'),
        ),
    ]
