# Generated by Django 2.1.5 on 2019-02-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0003_auto_20190218_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='m_unit',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='measuring units'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='open_date',
            field=models.DateField(blank=True, null=True, verbose_name='date opened'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='purity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='purity/percentage'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='ret_date',
            field=models.DateField(blank=True, null=True, verbose_name='retest date'),
        ),
    ]
