# Generated by Django 2.1.6 on 2019-03-06 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0004_auto_20190304_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='curr_amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='current amount'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_res',
            field=models.DateField(verbose_name='date of reservation'),
        ),
    ]
