# Generated by Django 2.1.5 on 2019-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0004_auto_20190218_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_unit',
            name='url',
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='cat_num',
            field=models.CharField(blank=True, max_length=255, verbose_name='catalog number'),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='is_inactive',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
