# Generated by Django 2.1.5 on 2019-02-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0005_auto_20190213_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_unit',
            name='measure_u',
        ),
    ]
