# Generated by Django 2.1.6 on 2019-03-07 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0005_auto_20190306_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_unit',
            name='watch',
            field=models.ManyToManyField(through='labbyims.Watching', to='labbyims.Department'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ManyToManyField(through='labbyims.Watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
