# Generated by Django 2.1.5 on 2019-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0006_remove_product_unit_measure_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='is_inactive',
            field=models.BooleanField(verbose_name='Archived'),
        ),
    ]
