# Generated by Django 2.1.6 on 2019-03-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0006_auto_20190307_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_unit',
            name='watch',
        ),
        migrations.AddField(
            model_name='product_unit',
            name='department',
            field=models.ManyToManyField(blank=True, default=None, through='labbyims.Watching', to='labbyims.Department'),
        ),
    ]
