# Generated by Django 2.1.6 on 2019-03-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labbyims', '0002_auto_20190307_1151'),
        ('labbyims', '0007_auto_20190307_1116'),
    ]

    operations = [
    ]
